"""initial_migration

Revision ID: 5161849cfe80
Revises: 
Create Date: 2025-10-19 13:20:26.117572

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5161849cfe80'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blogs',
    sa.Column('blog_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('author', sa.String(length=100), nullable=False),
    sa.Column('sources', sa.Text(), nullable=True),
    sa.Column('date_published', sa.Date(), nullable=False),
    sa.PrimaryKeyConstraint('blog_id')
    )
    op.create_table('products',
    sa.Column('product_id', sa.String(length=10), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('brand', sa.String(length=50), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('subcategory', sa.String(length=50), nullable=True),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('image_url', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('product_id')
    )
    op.create_table('product_specifications',
    sa.Column('spec_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.String(length=10), nullable=False),
    sa.Column('spec_name', sa.String(length=100), nullable=False),
    sa.Column('spec_value', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.product_id'], name='fk_spec_product', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('spec_id'),
    sa.UniqueConstraint('product_id', 'spec_name', name='uq_product_spec_name')
    )
    op.create_table('reviews',
    sa.Column('review_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.String(length=10), nullable=False),
    sa.Column('user_alias', sa.String(length=50), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('review_text', sa.Text(), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('subcategory', sa.String(length=50), nullable=True),
    sa.Column('brand', sa.String(length=50), nullable=True),
    sa.Column('date_posted', sa.DateTime(), nullable=True),
    sa.CheckConstraint('rating >= 1 AND rating <= 5', name='check_rating_range'),
    sa.ForeignKeyConstraint(['product_id'], ['products.product_id'], name='fk_review_product', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('review_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reviews')
    op.drop_table('product_specifications')
    op.drop_table('products')
    op.drop_table('blogs')
    # ### end Alembic commands ###
