"""Remove rating column from reviews

Revision ID: aef9814e841b
Revises: f135bad50b6e
Create Date: 2025-10-25 06:39:45.833182

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'aef9814e841b'
down_revision = 'f135bad50b6e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.alter_column('review_text',
               existing_type=sa.TEXT(),
               nullable=False)
        batch_op.alter_column('date_posted',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
        batch_op.drop_column('rating')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rating', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.alter_column('date_posted',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
        batch_op.alter_column('review_text',
               existing_type=sa.TEXT(),
               nullable=True)

    # ### end Alembic commands ###
