"""Update blogs table structure

Revision ID: f135bad50b6e
Revises: 5161849cfe80
Create Date: 2025-10-25 06:17:50.036855

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f135bad50b6e'
down_revision = '5161849cfe80'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('blogs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('introduction', sa.Text(), nullable=False))
        batch_op.add_column(sa.Column('body', sa.Text(), nullable=False))
        batch_op.add_column(sa.Column('conclusion', sa.Text(), nullable=False))
        batch_op.add_column(sa.Column('image_url', sa.String(length=255), nullable=True))
        batch_op.drop_column('content')
        batch_op.drop_column('sources')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('blogs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sources', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('content', sa.TEXT(), autoincrement=False, nullable=False))
        batch_op.drop_column('image_url')
        batch_op.drop_column('conclusion')
        batch_op.drop_column('body')
        batch_op.drop_column('introduction')

    # ### end Alembic commands ###
